### ISSUE TITLE
Bug on Dashboard Analytics 

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#372]

**Comment by brunovjk** [comment]
hello @salahlalami @Ando22, I would like to work on this. Could you provide more bug details?

**Comment by Ando22** [comment]
Hi @brunovjk 

Thank you for your interest! so the bug is the empty preview card analytics, In the middle section. currently, when the backend returns empty, it returns a blank section. the `frontend/src/modules/DashboardModule/components/PreviewCard.jsx` module component, should handle the empty state of the preview. we are open to any ideas for the handlers 👍 

<img width="1439" alt="Screen Shot 2023-08-30 at 15 03 01" src="https://github.com/idurar/idurar-erp-crm/assets/38315094/3260cd3b-544a-46cf-bd4e-d0f9e5e18779">

**Comment by brunovjk** [comment]
Very good @Ando22, thanks for the information, I'm on it.
I'll let you know if I have any ideas or questions.

**Comment by brunovjk** [comment]
Hey @Ando22,

I took a shot at solving the issue in the `PreviewCard` component. My approach involved using default values for display when the backend returns empty data. 

You can check out the changes I made on GitHub: [Link to Changes](https://github.com/idurar/idurar-erp-crm/compare/dev...brunovjk:idurar-erp-crm:issues/bug-on-dashboard-analytics)

I think this approach aligns well, considering other components on the same dashboard use `0` as default values. 
I'm curious to hear your thoughts! Was this along the lines of what you had in mind? Your feedback would be greatly appreciated.

**Comment by Ando22** [comment]
Hey @brunovjk 

Thank you for the solutions. I like it. I'm thinking that too. giving the default value for each status. for the preview card 👍 

cc: @salahlalami

**Comment by rkmdCodes** [comment]
hi @Ando22  @salahlalami  , I have already opened PR #378 way before   which is closing this issue.
Please review this.

https://github.com/idurar/idurar-erp-crm/assets/113243168/6362fbf6-149f-4d68-99dd-3650912e34ff
